"""empty message

Revision ID: 396ccd0a69c3
Revises: 9ee2423beeed
Create Date: 2025-08-27 13:40:26.139230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396ccd0a69c3'
down_revision = '9ee2423beeed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('announcements')
    # ### end Alembic commands ###
