"""empty message

Revision ID: 448fbfa858aa
Revises: 7416107ce2de
Create Date: 2025-08-26 02:01:33.296919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448fbfa858aa'
down_revision = '7416107ce2de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('profile_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'department', ['dept_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('profile_ibfk_2'), 'department', ['dept_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
