"""empty message

Revision ID: 7416107ce2de
Revises: eb054de999bc
Create Date: 2025-08-26 01:53:08.160099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7416107ce2de'
down_revision = 'eb054de999bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('department_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('profile_id')

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dept_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'department', ['dept_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('dept_id')

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('department_ibfk_1'), 'profile', ['profile_id'], ['id'])

    # ### end Alembic commands ###
