"""empty message

Revision ID: eb054de999bc
Revises: e2957fd84fbb
Create Date: 2025-08-26 01:40:32.463803

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb054de999bc'
down_revision = 'e2957fd84fbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('faculty_name'))

    op.drop_table('faculty')
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dept_code', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('faculty', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('est_year', sa.String(length=4), nullable=False))
        batch_op.add_column(sa.Column('hod', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['dept_code'])

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faculty', sa.String(length=100), nullable=True))
        batch_op.alter_column('level',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('faculty')

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('hod')
        batch_op.drop_column('est_year')
        batch_op.drop_column('faculty')
        batch_op.drop_column('dept_code')

    op.create_table('faculty',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('faculty_name', mysql.VARCHAR(length=190), nullable=False),
    sa.Column('profile_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name=op.f('faculty_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('faculty_name'), ['faculty_name'], unique=True)

    # ### end Alembic commands ###
